Fix/dependencies/request promise native
campudus/grud-aggregator pull request #16
Opened 2020-09-09 13:14 UTC by GeniusWigga

The grud-aggregator is not compatible with node version 14. The reason for this is the deprecated request-promise-native dependency. To be prepared for the future, this dependency has been replaced by axios.

2020-09-09 20:24 UTC, Zwergal requested changes

2020-09-09 20:24 UTC, Zwergal commented on package.json
> +    "axios": "^0.20.0",
Please remove ^ from the version to pin it the this specific version.

2020-09-09 21:20 UTC, McHunkyTrunk commented on CHANGELOG.md
> +## 7.0.2 - Remove deprecated `request-promise-native`
Use the past tense for the version description: "Removed ..."

2020-09-10 07:20 UTC, McHunkyTrunk approved these changes

2020-09-11 08:23 UTC, merged