Feat/extend step
campudus/grud-aggregator pull request #36
Opened 2023-05-23 10:59 UTC by McHunkyTrunk

Erweiterung für die `step()` Funktion um den `options` Parameter, um die Nachricht beim eigentlich Aufruf zu ersetzen oder die Meldung über `progress()` komplett zu unterdrücken.

2023-05-23 12:16 UTC, Zwergal requested changes

2023-05-23 12:21 UTC, McHunkyTrunk commented on lib/attachments/imageResizer.js
@Zwergal So wie es aussieht war diese acuh veraltet. Stimmt nun zumindest mit der Source überein.

2023-05-25 09:04 UTC, McHunkyTrunk commented on lib/attachments/imageResizer.js
@Zwergal Worauf sind "Changes requested" bezogen? Sollen wir die Datei in einem extra PR anpassen?

2023-05-25 09:27 UTC, Zwergal commented on lib/attachments/imageResizer.js
Ging um die Änderung an der Datei. Komisch, dass dieses Feature generell dann ging, wenn es eigentlich gar nicht im lib drin war. Wurde ja bereits genutzt in Projekten.

2023-05-25 09:28 UTC, Zwergal approved these changes

2023-05-25 22:11 UTC, merged